### ISSUE TITLE
Issues installing HERBS using MacBook M1 chip

### ISSUE THREAD

**Issue by ishiangoli** [JingyiGF/HERBS#5]
Hello

I have been having trouble trying to install HERBS following the instructions provided. The first issue that I encountered was that HERBS was not compatible with the pre installed version of Python on my Mac so I installed a different version of Python.

I then had trouble importing PyQt5 as again, Mac M1 is only compatible with PyQt6. I resolved this by running the terminal in Rosetta mode and it worked fine.

I now however receive this error:

ImportError: dlopen(/Users/irenieshiangoli/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so, 0x0002): tried: '/Users/irenieshiangoli/PycharmProjects/pythonProject/venv/lib/python3.10/site-packages/PyQt5/QtWidgets.abi3.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

I noticed in your instructions that HERBS has been tested with Mac however I think I need some more guidance for successfully installing it if possible - I do not have much experience in programming or coding so I might be missing something trivial.

Thank you!

**Comment by JingyiGF** [comment]
Hi, Thank you so much for this info. Honestly We do not have a M1 machine to test on. So we did not realise this. I saw someone has installed PyQt5 on M1 machine without through Rosetta when I search for this on Stackoverflow https://stackoverflow.com/questions/65901162/how-can-i-run-pyqt5-on-my-mac-with-m1chip. Not sure this helps or not. Sorry for the inconvenience, we can try to modify HERBS to make it suitable for PyQt6 later if it is a strong preference for you. Once again, thank you for the information. I will try to look for a M1 machine to test if possible. And please let us know if it works to reinstall PyQt5 according to the link.

**Comment by pbmanis** [comment]
I am providing this information as a potential roadmap. I haven't used this program yet, but have a good bit of experience making older PyQt-dependent programs running on M1's (acq4, neurodemo). I have a couple of M1's to test things on. There are a couple of things that have to be done to this codebase to make it run with PyQt6. One is to consistently do the PyQt# imports through pyqtgraph, instead of directly. This smooths over some - but not all - of the differences between PyQt versions.  Looking at the code for HERBS, this has been done in some, but not all, of the modules, and in some cases, the imports from pyqtgraph.Qt are not actually referenced in the modules. The other is that the format of direct calls via Qt have been changed in some cases (enums are now organized and one level down in the hierarchy). This requires the most work, including thorough testing.

**Comment by JingyiGF** [comment]
Thank you so much Paul. I really appreciate your help and advice.

**Comment by pbmanis** [comment]
Partial success getting this working with PyQt6 on M1, but still testing (also testing against x86_64 system). Can load/download and display the atlas, do rotations, different display modes, etc. Using a conda-based environment, mainly to have imagecodecs, which was not working from pip. I'll let you know when I think it the branch  is worth looking at. So far it looks pretty nice. My use case is computing electrode trajectories for recording (angled), and mapping brain slices cut at an odd angle (see Blackstad et al. 1984) onto the standard atlas.

**Comment by JingyiGF** [comment]
Thank you Paul, this is really helpful! Please let me know anything that I can do to make the workflow better :-)

**Comment by ishiangoli** [comment]
Thank you Jingyi and Paul for your help and advice, I look forward to hearing how you get on. Excited to start using this program :)

**Comment by mdiamantaki** [comment]
Hi, I was able to install herbs in my MacBook M1 without any errors. Also imported and run without problems. However, when downloading the Allen mice atlas (I followed the steps in the cookbook), the process never finishes, see screenshot attached. 

in the python terminal I get this output:
`(1320, 800, 1140)
[0, 0, 0]
(1140, 1320, 800)`

Any ideas?

(if you think I should open a new issue, please let me know)

Thanks! 
Maria

<img width="1403" alt="Screenshot 2022-09-28 at 2 21 58 PM" src="https://user-images.githubusercontent.com/60257179/192769526-56c2307d-6b66-459e-ac79-83ddc7109275.png">

**Comment by JingyiGF** [comment]
Hi Maria,

Thank you for the feedback. Good to know it works on your machine. If you open your local folder where you save the downloaded atlas, you will see even you choose the 10um atlas, the saving file is still 25um. I forgot to change the testing back before and I just updated the Github code and PyPI version to 0.0.15. Sorry for the inconvenience. About the output, the (1320, 800, 1140) means the original data shape of the atlas, [0, 0, 0] means the Allen mouse atlas has no specified Bregma as far as I know. If you have some idea about the Bregma of your own data and can related to the atlas, you can set it accordingly. Where (1140, 1320, 800) is the atlas shape after process. The process really takes some(long) time. I just re-processed my Allen 10um, and it takes around 40 mins. I understand you feel confused that it looks like it can never stop, but it will stop after some time. I will make this part more clear when I have time :-) For this time, please wait for it ;-)
<img width="640" alt="Screenshot 2022-09-28 at 14 38 42" src="https://user-images.githubusercontent.com/64961126/192780492-67a1bdaf-a63d-403b-8db2-d60e454755f0.png">

**Comment by mdiamantaki** [comment]
hey Jingyi,

thanks for the fast reply! Actually I wasn't clear enough.. the process never finishes. it is still the same as the screenshot I sent you. Also, these files have been created in the atlas folder

<img width="717" alt="Screenshot 2022-09-28 at 3 44 22 PM" src="https://user-images.githubusercontent.com/60257179/192782217-230da4af-07bd-4fd7-9747-7c6bf514cd0b.png">

Is the process done? should I manually close the windows? if I do so and then reopen and try to load the atlas, it doesn't load anything..

**Comment by JingyiGF** [comment]
Hey Maria, Sorry that I was not clear enough. I made some errors in the old version code. and I just updated the code. So you have to update HERBS to 0.0.15 if you install through PyPI. Or download the new code from GitHub. I am sure you can see the new update on GitHub. And then re-download the files and process it. you will have the files as shown in the screenshot. you can also see when I got  these files and approximately how long it will take. the last file contourpre_made.pkl takes really long time to get. hope this helps a bit. Please let me know if it works or not :-)
<img width="623" alt="Screenshot 2022-09-28 at 14 51 05" src="https://user-images.githubusercontent.com/64961126/192782984-563bfb6c-8874-49ff-a124-1a926663aeb9.png">

**Comment by mdiamantaki** [comment]
great, I'll go through the steps now and let you know! thanks a lot!

**Comment by ishiangoli** [comment]
Hi could you please specify how you installed HERBS on your MacBook M1?

**Comment by mdiamantaki** [comment]
I installed HERBS with pip. I don't use a conda environment, neither rosetta. However, I had already installed qt5 some months ago (I needed it for another package) and I think I troubleshoot a lot at the time, but now I don't remember how I successfully installed it at the end

**Comment by mdiamantaki** [comment]
I still have the same problem, I installed HERBS 0.0.15 and re-download the mouse atlas.. the process never ends. The files are created and have the same size as in your case @JingyiGF, apart from the contour_pre_made.pkl that is not generated at all. I don't get any error messages.

I tried to install the rat atlas, everything went smooth and I was able to load it and go through it. 

Is there another way of processing the downloaded atlas? Any alternatives? 
Thanks!

**Comment by JingyiGF** [comment]
Hi again, Maria, Could you try a 25um instead to see if it works? the 10um takes loooooooong time to generate contour_pre_made.pkl. and also it is pretty big. I can update the code to let HERBS not require that file for testing if you want. Just wondering how long time did you wait for it to process? And do you have enough disk space for the file? Will update you when I am done with it.

**Comment by mdiamantaki** [comment]
I am trying the 25um now. I waited for 2-3 hours for sure and I have enough disk space.

**Comment by mdiamantaki** [comment]
it works with the 25um!

**Comment by JingyiGF** [comment]
I think it just not finish when you do for the 10um. Some machines are faster and some slower.  I will modify the code to make that file smaller so that it will not be so painful to process it later. Will update you when I upload the code.

**Comment by mdiamantaki** [comment]
Thanks for the help! I think I am ok with the 25 for the time being, it should be enough to explore HERBS.

**Comment by JingyiGF** [comment]
Hi Maria,

I update the code for 10um. It should give you a better experience I hope :-)

Best,
Jingyi

**Comment by David-Omer** [comment]
Hi Jingyi, 
I'm trying to install the latest version of HERBS from PyPl and I get the following error: 
<img width="935" alt="Screenshot 2023-12-12 at 15 37 12" src="https://github.com/JingyiGF/HERBS/assets/87187297/ba30f1e9-aaa4-4f6c-b5f2-d8aab3a16d44">

Your help is much appriciated. 
Thanks, 
Didi
